version: '3.8'

services:
  backend:
    container_name: gronthagar-backend
    build:
      context: ./
      dockerfile: ./src/backend/Dockerfile
    volumes:
      - ./src/backend:/src/backend
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload